# Generated by Django 4.1.1 on 2022-09-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fromage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('origin', models.CharField(blank=True, max_length=100, verbose_name='origine')),
                ('category', models.CharField(blank=True, choices=[('PMO', 'patemolles'), ('PPC', 'patepresseescuites'), ('PFL', 'patefleuries'), ('FCH', 'fromagedechevres'), ('FBR', 'fromagedebrebis'), ('PPE', 'patepersillees'), ('TCR', 'triplecremes'), ('PFO', 'patefortes')], max_length=100, verbose_name='categorie')),
                ('description', models.TextField(blank=True)),
                ('composition', models.CharField(blank=True, max_length=100)),
                ('stock', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='Fromages')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='prix')),
            ],
        ),
    ]
